### ISSUE TITLE
[Color system] New minor version with Sass variables from polaris-react

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-tokens#75]

**Comment by kaelig** [comment]
As discussed with Dan, we're going to be releasing beta versions for now, so we can introduce breaking changes and large refactors as we learn over the next few weeks.

**Comment by kaelig** [comment]
We discussed we'd want to use camelCase in all languages, as this single notation will make it easier to search for tokens across a codebase.

Moving from kebab-case to camelCase is a breaking change for consumers already using variables instead of helper functions.

I don't think it's worth looking for a smooth upgrade path here, since most of our consumers use helper functions and won't be impacted by this.

For this reason, I recommend introducing a breaking change when bringing Sass variables from polaris-react in polaris-tokens.

**Comment by danrosenthal** [comment]
Closed in favor of https://github.com/Shopify/polaris-react/issues/1982
